# Generated by Django 4.0.3 on 2022-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
